#!/usr/bin/env python3
"""
Setup new Jira project for test case management
"""
import os
import requests
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

def create_jira_project():
    """Create a new Jira project for test cases"""
    
    print("=== Jira Project Setup ===")
    
    # Get Jira credentials
    jira_url = os.getenv("JIRA_API_URL")
    jira_user = os.getenv("JIRA_USER")
    jira_token = os.getenv("JIRA_TOKEN")
    
    if not all([jira_url, jira_user, jira_token]):
        print("ERROR: Missing Jira credentials in .env file")
        return False
    
    auth = (jira_user, jira_token)
    
    # Project details
    project_key = "TESTCASE"
    project_name = "Test Case Management"
    
    try:
        # Check if project already exists
        check_url = f"{jira_url}/rest/api/2/project/{project_key}"
        check_response = requests.get(check_url, auth=auth, timeout=10)
        
        if check_response.status_code == 200:
            print(f"Project {project_key} already exists!")
            project_data = check_response.json()
            print(f"Project Name: {project_data['name']}")
            print(f"Project Key: {project_data['key']}")
            return project_key
        
        # Create new project
        create_url = f"{jira_url}/rest/api/2/project"
        
        project_payload = {
            "key": project_key,
            "name": project_name,
            "projectTypeKey": "software",
            "projectTemplateKey": "com.pyxis.greenhopper.jira:gh-simplified-agility-kanban",
            "description": "Project for managing automated test cases generated by the Multi-Agent RAG system",
            "lead": jira_user,
            "assigneeType": "PROJECT_LEAD"
        }
        
        print(f"Creating project: {project_name} ({project_key})")
        create_response = requests.post(create_url, json=project_payload, auth=auth, timeout=30)
        
        if create_response.status_code == 201:
            project_data = create_response.json()
            print(f"✅ Project created successfully!")
            print(f"Project Key: {project_data['key']}")
            print(f"Project ID: {project_data['id']}")
            return project_data['key']
        else:
            print(f"Failed to create project: {create_response.status_code}")
            print(f"Response: {create_response.text}")
            
            # Try with simpler payload
            simple_payload = {
                "key": project_key,
                "name": project_name,
                "projectTypeKey": "software",
                "lead": jira_user
            }
            
            print("Trying with simplified project creation...")
            simple_response = requests.post(create_url, json=simple_payload, auth=auth, timeout=30)
            
            if simple_response.status_code == 201:
                project_data = simple_response.json()
                print(f"✅ Project created with simple template!")
                print(f"Project Key: {project_data['key']}")
                return project_data['key']
            else:
                print(f"Simple creation also failed: {simple_response.status_code}")
                print(f"Response: {simple_response.text}")
                return False
                
    except Exception as e:
        print(f"Error creating project: {e}")
        return False

def update_env_file(project_key):
    """Update .env file with new project key"""
    try:
        # Read current .env file
        with open('.env', 'r') as f:
            lines = f.readlines()
        
        # Update JIRA_PROJECT_KEY line
        updated_lines = []
        for line in lines:
            if line.startswith('JIRA_PROJECT_KEY='):
                updated_lines.append(f'JIRA_PROJECT_KEY="{project_key}"\n')
            else:
                updated_lines.append(line)
        
        # Write updated .env file
        with open('.env', 'w') as f:
            f.writelines(updated_lines)
        
        print(f"✅ Updated .env file with JIRA_PROJECT_KEY=\"{project_key}\"")
        return True
        
    except Exception as e:
        print(f"Error updating .env file: {e}")
        return False

def main():
    """Main setup function"""
    print("Setting up Jira project for test case management...")
    
    project_key = create_jira_project()
    
    if project_key:
        if update_env_file(project_key):
            print(f"\n🎉 Setup complete!")
            print(f"Project Key: {project_key}")
            print(f"You can now run the main system to create test cases in Jira.")
        else:
            print(f"\n⚠️ Project created but failed to update .env file")
            print(f"Please manually update JIRA_PROJECT_KEY=\"{project_key}\" in your .env file")
    else:
        print(f"\n❌ Failed to create Jira project")
        print("Please check your Jira credentials and permissions")

if __name__ == "__main__":
    main()